
package windows;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import metromendeley.Functions;
import metromendeley.GlobalVariables;
import metromendeley.InfoObject;


/**
 *
 * @author victorpointud
 */
public class Add extends javax.swing.JFrame {

    public Add() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        Choose = new javax.swing.JButton();
        PathDisplay = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Resumen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Menu.setBackground(new java.awt.Color(153, 153, 255));
        Menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 50));

        Choose.setBackground(new java.awt.Color(204, 204, 255));
        Choose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Choose.setText("Elegir");
        Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseActionPerformed(evt);
            }
        });
        jPanel1.add(Choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 80, 40));

        PathDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(PathDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 320, 40));

        Add.setBackground(new java.awt.Color(255, 255, 102));
        Add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add.setText("Agregar");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Add.jpg")));
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Menu m = new Menu();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    private void ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseActionPerformed
        JFileChooser fc = new JFileChooser();
        int selection = fc.showOpenDialog(this);
        
        if (selection == JFileChooser.APPROVE_OPTION) {
            File path = fc.getSelectedFile();
            PathDisplay.setText(path.getAbsolutePath());
        }
    }//GEN-LAST:event_ChooseActionPerformed

    private void PathDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathDisplayActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if (PathDisplay.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "No se ha agregado ningún elemento.");
        }
        else{ 
            Functions functions = new Functions();
            String w = functions.readText(PathDisplay.getText());
            InfoObject summary = functions.createObjects(w);
            if (!GlobalVariables.getTable().search2(summary)) {
                GlobalVariables.getTable().insert(summary);
                GlobalVariables.getList().insertEnd(summary.getTitle());
                GlobalVariables.getObjects().insertEnd2(summary);
//                GlobalVariables.getObjects().insertEnd2(summary);
                functions.writeText(PathDisplay.getText());
            }
            else{
                JOptionPane.showMessageDialog(null, "Ya el resumen ha sido agregado.");
            } 
        }


    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Choose;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField PathDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
