
package windows;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import metromendeley.GlobalVariables;
import metromendeley.List;
import metromendeley.Node;
import metromendeley.Functions;
import javax.swing.JLabel;
import javax.swing.ImageIcon;

/**
 *
 * @author victorpointud
 */

public final class Analysis extends javax.swing.JFrame {

    private ImageIcon image;
    private Icon icon;
    
    public Analysis() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.printImage(this.jLabel1, "src/pictures/Analysis.jpg");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        AllTitles();
    }
    
    public void AllTitles() {
        List lista = GlobalVariables.getList();
        Node pointer = lista.getHead();
        int index = 0;
        while (pointer != null) {
            String titulo = pointer.getElement();
            Titles.insertItemAt(titulo, index);
            index++;
            pointer = pointer.getNext();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Titles = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextArea();
        Menu = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Analizar Resumen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        Titles.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Titles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitlesActionPerformed(evt);
            }
        });
        jPanel1.add(Titles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 40));

        Info.setColumns(20);
        Info.setRows(5);
        jScrollPane1.setViewportView(Info);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 450, 220));

        Menu.setBackground(new java.awt.Color(255, 255, 153));
        Menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, 40));

        Add.setBackground(new java.awt.Color(204, 255, 204));
        Add.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Add.setText("Agregar");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Analysis.jpg")));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Menu m = new Menu();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    private void TitlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitlesActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        Functions v = new Functions();
        if (Titles.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "No se ha agregado ningún elemento.");
        }
        else{
            String p = GlobalVariables.getTable().searchObject(String.valueOf(Titles.getSelectedItem())).createInfo();
            Info.setText(p);
        }
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analysis().setVisible(true);
            }
        });
    }
    
    private void printImage(JLabel label, String rute){
        this.image = new ImageIcon(rute);
        this.icon = new ImageIcon(
       this.image.getImage().getScaledInstance(
               label.getWidth(),
              label.getHeight(),
               Image.SCALE_DEFAULT
            )
        );
        jLabel1.setIcon(this.icon);
        this.repaint();
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextArea Info;
    private javax.swing.JButton Menu;
    private javax.swing.JComboBox<String> Titles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
