
package windows;

/**
 *
 * @author victorpointud
 */

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddInfo = new javax.swing.JButton();
        AnalyseInfo = new javax.swing.JButton();
        Author = new javax.swing.JButton();
        End = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        KeyWord = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        AddInfo.setBackground(new java.awt.Color(255, 255, 204));
        AddInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddInfo.setText("Agregar Resumen");
        AddInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInfoActionPerformed(evt);
            }
        });
        jPanel1.add(AddInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 70));

        AnalyseInfo.setBackground(new java.awt.Color(153, 153, 255));
        AnalyseInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AnalyseInfo.setText("Analizar Resúmenes");
        AnalyseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseInfoActionPerformed(evt);
            }
        });
        jPanel1.add(AnalyseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, 70));

        Author.setBackground(new java.awt.Color(255, 153, 153));
        Author.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Author.setText("Autor");
        Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorActionPerformed(evt);
            }
        });
        jPanel1.add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 80));

        End.setBackground(new java.awt.Color(153, 255, 153));
        End.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        End.setText("Salir");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        jPanel1.add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 90, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Busqueda por:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, 20));

        KeyWord.setBackground(new java.awt.Color(255, 153, 153));
        KeyWord.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        KeyWord.setText("Palabra Clave");
        KeyWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyWordActionPerformed(evt);
            }
        });
        jPanel1.add(KeyWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 200, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Menu.jpeg")));
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorActionPerformed
        Author au = new Author();
        this.setVisible(false);
        au.setVisible(true);
    }//GEN-LAST:event_AuthorActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        Start i = new Start();
        this.setVisible(false);
        i.setVisible(true) ;
    }//GEN-LAST:event_EndActionPerformed

    private void AddInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInfoActionPerformed
        Add a = new Add();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_AddInfoActionPerformed

    private void AnalyseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseInfoActionPerformed
        Analysis an = new Analysis();
        this.setVisible(false);
        an.setVisible(true);
    }//GEN-LAST:event_AnalyseInfoActionPerformed

    private void KeyWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyWordActionPerformed
        KeyWord p = new KeyWord();
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_KeyWordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInfo;
    private javax.swing.JButton AnalyseInfo;
    private javax.swing.JButton Author;
    private javax.swing.JButton End;
    private javax.swing.JButton KeyWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
