
package windows;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import metromendeley.Functions;
import metromendeley.GlobalVariables;
import metromendeley.InfoObject;

/**
 *
 * @author victorpointud
 */

public class Start extends javax.swing.JFrame {
    
    private ImageIcon image;
    private Icon icon;
    
    public Start() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.printImage(this.jLabel1, "src/pictures/Start.jpg");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        EndAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("MetroMendeley");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel4.setText("Creado por Victor Pointud.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Administración De Artículos Científicos.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 20));

        Start.setBackground(new java.awt.Color(255, 204, 255));
        Start.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Start.setText("Empezar");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, 80));

        EndAll.setBackground(new java.awt.Color(153, 153, 255));
        EndAll.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EndAll.setText("Salir");
        EndAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndAllActionPerformed(evt);
            }
        });
        jPanel1.add(EndAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 160, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Start.jpg")));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        Functions functions = new Functions();
        String w = functions.readText("test\\total.txt");
        String[] textLineSplit = w.split("\n");
        for (int i = 0; i < textLineSplit.length; i++) {
            String summary = functions.readText(textLineSplit[i]);
            InfoObject object = functions.createObjects(summary);
            if (!GlobalVariables.getTable().search2(object)) {
                GlobalVariables.getList().insertEnd(object.getTitle());
                GlobalVariables.getTable().insert(object);
                GlobalVariables.getObjects().insertEnd2(object);
            }
        }
        Menu m = new Menu();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_StartActionPerformed

    private void EndAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndAllActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EndAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }
    
    private void printImage(JLabel label, String rute){
        this.image = new ImageIcon(rute);
        this.icon = new ImageIcon(
       this.image.getImage().getScaledInstance(
               label.getWidth(),
              label.getHeight(),
               Image.SCALE_DEFAULT
            )
        );
        jLabel1.setIcon(this.icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EndAll;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
